sudo: false
dist: trusty
group: stable

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba

language: scala

jdk:
  - oraclejdk8

matrix:
  fast_finish: true

matrix:
  include:
  - env: SBT_CMD="scripted java/*"
    before_install:
      - curl -sL https://raw.githubusercontent.com/shyiko/jabba/master/install.sh | JABBA_VERSION=0.9.6 bash && . ~/.jabba/jabba.sh
    install:
      - /home/travis/.jabba/bin/jabba install openjdk@1.10

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

script:
  # It doesn't need that much memory because compile and run are forked
  - /home/travis/.jabba/jdk/openjdk@1.10.0/bin/java --version

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
